### ISSUE TITLE
controller error

### ISSUE THREAD

**Issue by aatayb** [GAR-Project/project#4]
Hi
this error appear when run controller 
#ryu-manager ryu.app.simple_switch_13

Traceback (most recent call last):
  File "/usr/bin/ryu-manager", line 9, in <module>
    load_entry_point('ryu==3.30', 'console_scripts', 'ryu-manager')()
  File "/usr/lib/python2.7/dist-packages/ryu/cmd/manager.py", line 68, in main
    log.init_log()
  File "/usr/lib/python2.7/dist-packages/ryu/log.py", line 79, in init_log
    disable_existing_loggers=False)
  File "/usr/lib/python2.7/logging/config.py", line 85, in fileConfig
    handlers = _install_handlers(cp, formatters)
  File "/usr/lib/python2.7/logging/config.py", line 163, in _install_handlers
    h = klass(*args)
  File "/usr/lib/python2.7/logging/handlers.py", line 391, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib/python2.7/logging/__init__.py", line 913, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python2.7/logging/__init__.py", line 943, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 2] No such file or directory: '/var/log/ryu/ryu.log'

**Comment by pcolladosoto** [comment]
Hi @aatayb! Are you still struggling with this issue?

**Comment by PoonamTrimbake** [comment]
can have the passwords

**Comment by pcolladosoto** [comment]
Hi @PoonamTrimbake. What's your question exactly? 🤔

**Comment by pcolladosoto** [comment]
We're closing this issue due to inactivity. Feel free to continue the conversation if the issue persists!
